version: 2
models:
  - name: gold_auditorias_consolidadas
    columns:
      - name: id_auditoria
        tests:
          - not_null
      - name: data_submissao
        tests:
          - not_null
      - name: nome_empresa
        tests:
          - not_null
      - name: setor_avaliado
        tests:
          - not_null
      - name: pergunta_formatada
        tests:
          - not_null
      - name: resposta
        tests:
          - accepted_values:
              arguments: 
                values: ['Conforme', 'Não conforme', 'N/A']